/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class opencv3_com_cvcamera_DetectionBasedTracker */

#ifndef _Included_opencv3_com_cvcamera_DetectionBasedTracker
#define _Included_opencv3_com_cvcamera_DetectionBasedTracker
#ifdef __cplusplus
extern "C" {
#endif

  /*
   * Class:     opencv3_com_cvcamera_DetectionBasedTracker
   * Method:    nativeSetFaceSize
   * Signature: (JI)V
   */
  JNIEXPORT void JNICALL Java_opencv3_com_cvcamera_DetectionBasedTracker_loadCascadeFile
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     opencv3_com_cvcamera_DetectionBasedTracker
 * Method:    nativeDetect
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_opencv3_com_cvcamera_DetectionBasedTracker_nativeDetect
  (JNIEnv *, jclass, jlong, jlong, jlong);


/*
 * Class:     opencv3_com_cvcamera_DetectionBasedTracker
 * Method:    nativeDetect
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_opencv3_com_cvcamera_DetectionBasedTracker_nativeCutImageROI
        (JNIEnv *, jclass, jlong, jlong, jlong, jlong);


#ifdef __cplusplus
}
#endif
#endif
